spring:
    datasource:
        #url: jdbc:postgresql://localhost:15432/kintaidb
        #username: postgres
        #password: postgres
        url: ${JDBC_DATABASE_URL}
        username: ${JDBC_DATABASE_USERNAME}
        password: ${JDBC_DATABASE_PASSWORD}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
      
            
      