spring:
    thymeleaf:
        cache: false
        mode: LEGACYHTML5
        prefix: classpath:/static/
    datasource:
        #url: jdbc:postgresql://localhost:15432/kintaidb
        #username: postgres
        #password: postgres
        url: ${JDBC_DATABASE_URL}
        username: ${JDBC_DATABASE_USERNAME}
        password: ${JDBC_DATABASE_PASSWORD}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
#    session:
#        store-type: redis
#    redis:
#        host: localhost
#        port: 6379
    messages:
      cache-seconds: -1
      basename: messages
      encoding: UTF-8
    mail:
      default-encoding: UTF-8
      protocol: smtp
      host: smtp.gmail.com
      port: 587
      username: h.ono@frevo-works.co.jp
      password: children
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              #enable: false
              enable: true
            #socketFactory:
            #  port: 587
            #  class: javax.net.ssl.SSLSocketFactory
            #  fallback: false
          #debug: true
      #test-connection: false
      
            
      